version: 0.0
os: ubuntu
 
files:
  - source: /
    destination: /var/www/html
    overwrite: true
 
permissions:
  - object: /var/www/html
    pattern: "**"
    owner: www-data
    group: www-data


hooks:
  BeforeInstall:
    - location: scripts/before_install.sh
      timeout: 300
      runas: root
 
  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300
      runas: root